name: arcore_flutter_plugin
description: Flutter plugin for ARCore SDK, Android platform to build new augmented reality experiences
version: 0.0.11
homepage: https://github.com/giandifra/arcore_flutter_plugin

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.10.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8
  meta: ^1.1.8
  equatable: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.difrancescogianmarco.arcore_flutter_plugin
        pluginClass: ArcoreFlutterPlugin

